# -*- coding: utf-8 -*-
"""lab7 - 52000668

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aJ0Mjf8MBiTkrp4LWqCvlw8gjfoJPBLm
"""

import matplotlib.pyplot as plt
import math

def generator_data(a, b, size):
  n = (b - a) / (size - 1)
  result = []
  s = a
  while s < b:
    result.append(s)
    s += n;
  if len(result) < size:
    result.append(b)
  return result

# X = generator_data(4, 6, 100)
# print(X)

# UNIFORM DISTRIBUTION
def pmf_uniform_cont(a, b):
  return 1 / (b - a)

def plot_pmf_uniform_cont(a, b):
  # Plot the probability mass function of Uniform(a, b)
  X = generator_data(a, b, 100)
  if b != a:
    P = [pmf_uniform_cont(a, b) for x in X]
  
  plt.plot(X, P, '-')
  plt.plot([a, a], [0, 1 / (b - a)], 'g--')
  plt.plot([b, b], [0, 1 / (b - a)], 'g--')

  plt.title('PDF of Uniform continuous distribution(%.2f, %.2f)' % (a, b))
  plt.show()

plot_pmf_uniform_cont(4, 6)

# NORMAL DISTRIBUTION
def pmf_normal(x, mu, sigma):
  return (1 / math.sqrt(2 * math.pi * sigma * sigma)) * math.pow(math.e, ( - math.pow((x - mu), 2) / (2 * sigma * sigma)))

def cdf_normal(x, mu, sigma):
  return 0.5 * (1 + math.erf((x - mu) / (sigma * math.sqrt(2))))

def plot_pmf_normal(mu, sigma):
  # Plot the probability mass function of Normal(mu, sigma)

  X = generator_data(mu - 4 * sigma, mu + 4 * sigma, 1000)
  P_normal = [pmf_normal(x, mu, sigma) for x in X]
  
  plt.plot(X, P_normal, '-')
  plt.title('PMF of Normal(%.2f, %.2f)' %(mu, sigma))
  plt.xlabel('X')
  plt.ylabel('P')
  plt.show()

plot_pmf_normal(0, 1.5)

# EXERCISES 
# 1
def plot_cdf_normal(mu, sigma):
  # Plot the Cumulative distribution function of Normal(mu, sigma)
  X = generator_data(mu - 4 * sigma, mu + 4 * sigma, 1000)
  P_normal = [cdf_normal(x, mu, sigma) for x in X]
  
  plt.plot(X, P_normal, 'r-')
  plt.title('CDF of Normal(%.2f, %.2f)' %(mu, sigma))
  plt.xlabel('X')
  plt.ylabel('P')
  plt.show()

print("Exercises 1")
plot_cdf_normal(0, 1.5)

# 2
mu = 10
sigma = 1
result = cdf_normal(12, mu, sigma) - cdf_normal(9, mu, sigma)
print("Exercises 2")
print(result)