# -*- coding: utf-8 -*-
"""lab9 - 52000668

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A5KGMo9lkVMTSTRbIewvOFg79EIY372X

# line charts
"""

import matplotlib.pyplot as plt
import numpy as np

samples = [0.895, 0.91, 0.919, 0.926, 0.929, 0.931]
plt.plot(samples)

import matplotlib.pyplot as plt
import numpy as np

years = [2010, 2011, 2012, 2013, 2014, 2015]
samples = [0.895, 0.91, 0.919, 0.926, 0.929, 0.931]
plt.plot(years, samples)
plt.xlabel('year')
plt.ylabel('yield')

from matplotlib import markers
import matplotlib.pyplot as plt
import numpy as np

years = range(2000, 2012)
apples = [0.895, 0.91, 0.919, 0.926, 0.929, 
          0.931, 0.934, 0.936, 0.937, 0.9375, 
          0.933, 0.935]
oranges = [0.962, 0.941, 0.930, 0.923, 0.918, 
           0.908, 0.907, 0.904, 0.901, 0.898,
           0.90, 0.901]

plt.plot(years, apples)
plt.plot(years, oranges)
plt.xlabel('year')
plt.ylabel('yield')
plt.title('Crop yields in Kanto')
plt.legend(['Apples', 'Oranges'])
plt.show()

import matplotlib.pyplot as plt
import numpy as np

plt.plot(years, apples, marker='o')
plt.plot(years, oranges, marker='x')
plt.xlabel('year')
plt.ylabel('yield')
plt.title('Crop yields in Kanto')
plt.legend(['Apples', 'Oranges'])
plt.show()

plt.figure(figsize=(9, 3))
plt.plot(years, apples, marker='*')
plt.show()

"""# scatter plot

"""

import matplotlib.pyplot as plt
import numpy as np

girls_grades = np.random. randint(100, size=30)
boys_grades = np.random. randint(100, size=30)
grades_range = np.random.randint(100, size=30)

fig = plt.figure(figsize=(3, 3))
ax = fig.add_axes([0, 0, 1, 1])
ax.scatter(grades_range, girls_grades, color='r')
ax.scatter(grades_range, boys_grades, color='b')
ax.set_xlabel('grades range')
ax.set_ylabel('grades scored')
ax.set_title('scatter plot')
plt.show()

"""# bar graphs"""

years = range(2000, 2006)
oranges = [0.4, 0.8, 0.9, 0.7, 0.6, 0.8]

plt.xlabel('year')
plt.ylabel('yield')
plt.bar(years, oranges)
plt.show()

apples = [0.35, 0.6, 0.9, 0.8, 0.65, 0.8]
plt.bar(years, apples)
plt.bar(years, oranges, bottom=apples)
plt.show()

data = [[30, 25, 50, 20],
        [40, 23, 51, 17]]

x = np.arange(4)
fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
ax.bar(x + 0.00, data[0], color = 'r', width = 0.25)
ax.bar(x + 0.25, data[1], color = 'm', width = 0.25)
ax.set_xticks([0.25, 1.25, 2.25, 3.25])
ax.set_xticklabels([2015, 2016, 2017, 2018])
ax.legend(labels=['Oranges', 'Apples'])
plt.show()

"""# histogram"""

fig, ax = plt.subplots(1, 1)
a = np.array([72, 87, 5, 73, 56, 73, 55, 53, 11, 20, 51, 5, 79, 31, 27])
ax.hist(a, bins = [0, 25, 50, 75, 100])
ax.set_title('histogram of result')
ax.set_xticks([0, 25, 50, 75, 100])
ax.set_xlabel('marks')
ax.set_ylabel('no. of students')
plt.show()

"""# exercises

# 1
"""

import pandas as pd
import math

data = pd.read_csv("iris.csv", delimiter=",")
data = pd.DataFrame(data)
# print(data)

# 1.1
# fig = plt.figure(figsize=(4, 3))
fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
ax.scatter(data['sepal_length'], data['sepal_width'], color='r')
ax.set_xlabel('sepal_length')
ax.set_ylabel('sepal_width')
ax.set_title('a simple scatter of sepal_length and sepal_width')
plt.show()

# 1.2
fig, ax = plt.subplots(1, 1)
ax.hist(data['sepal_length'], bins = [i for i in range(21)])
# ax.hist(data['sepal_length'], bins = [i for i in range(round(min(data['sepal_length'])) - 1, round(max(data['sepal_length'])) + 2)])
ax.set_title('histogram of sepal_length')
ax.set_xticks([i for i in range(21)])
# ax.set_xticks([i for i in range(round(min(data['sepal_length'])) - 1, round(max(data['sepal_length'])) + 2)])
ax.set_xlabel('sepal_length')
ax.set_ylabel('frequency')
plt.show()

"""# 2"""

import pandas as pd

data = pd.read_csv("company-sales_data.csv", delimiter=",")
data = pd.DataFrame(data)
# print(data)

# a
plt.plot(data['total_profit'])
plt.title('$\it{Exercise 2.1}$')


# b
# read all month of toothpaste sales data and show it using a scatter plot
fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
ax.set_title('$\it{Exercise 2.2}$')
ax.scatter(range(len(data)), data['toothpaste'])
plt.show()

# c
x = np.arange(len(data))
fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
ax.bar(x + 0.00, data['facewash'], color = 'r', width = 0.25)
ax.bar(x + 0.25, data['facecream'], color = 'm', width = 0.25)
ax.set_xticks([i + 0.25 for i in range(len(data))])
ax.set_xticklabels([i + 1 for i in range(len(data))])
ax.set_title('$\it{Exercise 2.3}$')
ax.legend(labels=['Facewash', 'Facecream'])
plt.show()

"""# 3"""

import regex 
import itertools

plaintext = "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
plaintext += "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc."
plaintext += '''
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
'''

# remove all special character
plaintext = regex.sub('[^A-Za-z0-9]+', ' ', plaintext)
# print(plaintext.split(' '))
# print(len(plaintext.split(' ')))

plaintext = plaintext.split(' ')
wordCount = {}
for i in plaintext:
  if i in wordCount:
    wordCount[i] += 1
  else:
    wordCount[i] = 1


print(dict(reversed(sorted(wordCount.items(), key=lambda item: item[1]))))
input = dict(reversed(sorted(wordCount.items(), key=lambda item: item[1])))
input = dict(itertools.islice(input.items(), 30))

# print(input)
# print(len(input))
print(list(input.keys()))
print(list(input.values()))

ticks = list(input.keys())
plt.xticks([i for i in range(len(ticks))], ticks, rotation = 90)
plt.plot(list(input.values()))
plt.show()